/* Generated By:JavaCC: Do not edit this line. J48ParserConstants.java */
package wekadancer.parsers;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface J48ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHILD = 6;
  /** RegularExpression Id. */
  int THEN = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int OR = 9;
  /** RegularExpression Id. */
  int OPR = 10;
  /** RegularExpression Id. */
  int CPR = 11;
  /** RegularExpression Id. */
  int DIV = 12;
  /** RegularExpression Id. */
  int GT = 13;
  /** RegularExpression Id. */
  int LT = 14;
  /** RegularExpression Id. */
  int EQ = 15;
  /** RegularExpression Id. */
  int LE = 16;
  /** RegularExpression Id. */
  int GE = 17;
  /** RegularExpression Id. */
  int NE = 18;
  /** RegularExpression Id. */
  int INT = 19;
  /** RegularExpression Id. */
  int HEX = 20;
  /** RegularExpression Id. */
  int ID = 21;
  /** RegularExpression Id. */
  int BOOL = 22;
  /** RegularExpression Id. */
  int FLOAT = 23;
  /** RegularExpression Id. */
  int STRING = 24;
  /** RegularExpression Id. */
  int FUNCTION = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"|\"",
    "<THEN>",
    "<AND>",
    "<OR>",
    "\"(\"",
    "\")\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "<EQ>",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "<INT>",
    "<HEX>",
    "<ID>",
    "<BOOL>",
    "<FLOAT>",
    "<STRING>",
    "<FUNCTION>",
  };

}
