/* Generated By:JavaCC: Do not edit this line. PSDLParserConstants.java */
package wekadancer.parsers;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PSDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PS = 6;
  /** RegularExpression Id. */
  int ENDPS = 7;
  /** RegularExpression Id. */
  int GROUP = 8;
  /** RegularExpression Id. */
  int BEGIN = 9;
  /** RegularExpression Id. */
  int END = 10;
  /** RegularExpression Id. */
  int IF = 11;
  /** RegularExpression Id. */
  int THEN = 12;
  /** RegularExpression Id. */
  int AND = 13;
  /** RegularExpression Id. */
  int OR = 14;
  /** RegularExpression Id. */
  int OBR = 15;
  /** RegularExpression Id. */
  int CBR = 16;
  /** RegularExpression Id. */
  int GT = 17;
  /** RegularExpression Id. */
  int LT = 18;
  /** RegularExpression Id. */
  int EQ = 19;
  /** RegularExpression Id. */
  int LE = 20;
  /** RegularExpression Id. */
  int GE = 21;
  /** RegularExpression Id. */
  int NE = 22;
  /** RegularExpression Id. */
  int INT = 23;
  /** RegularExpression Id. */
  int HEX = 24;
  /** RegularExpression Id. */
  int ID = 25;
  /** RegularExpression Id. */
  int BOOL = 26;
  /** RegularExpression Id. */
  int FLOAT = 27;
  /** RegularExpression Id. */
  int STRING = 28;
  /** RegularExpression Id. */
  int COMPONENT_FUNCTION = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"PS\"",
    "\"ENDPS\"",
    "\"GROUP\"",
    "\"BEGIN_G\"",
    "\"END_G\"",
    "\"IF\"",
    "\"THEN\"",
    "\"AND\"",
    "\"OR\"",
    "\"{\"",
    "\"}\"",
    "\">\"",
    "\"<\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "<INT>",
    "<HEX>",
    "<ID>",
    "<BOOL>",
    "<FLOAT>",
    "<STRING>",
    "<COMPONENT_FUNCTION>",
    "\",\"",
    "\";\"",
  };

}
